### ISSUE TITLE
v3.1.1 Access Control

### ISSUE THREAD

**Issue by go-faustino** [sapplica/sentrifugo#103]
Hi, 

In your 3.1.1 release, 'getmoreemployees' wasn't added to access control, so it's not possible to get the remaining employees.

**Comment by CarBee** [comment]
Please Fix the same.

**Comment by sapplica** [comment]
Hi,

@go-faustino Kindly update any one of the records in 'Roles & Privileges'. Go to: HR › Roles & Privileges. Thank you!

**Comment by go-faustino** [comment]
Thanks, it adds the missing controls.
