### ISSUE TITLE
Can't Add Expenses and Assets Modules

### ISSUE THREAD

**Issue by shameera91** [sapplica/sentrifugo#131]
I have successfully configured the sentrifugo HRMS system and it works fine. But the sentrifugo 3.0 gives two new modules which are Expenses and Assets. I have added the source code to my existing project. After adding I accessed the modules . but it always shows 404 error. 
I checked the Access Controller file and found that the necessary lines for assets and expenses are not there. If I add those manually all works fine. But I update the roles and privileges , the it doesn't work. I have attached a screenshot here with, which is generated after updating roles and privileges. 
Can you tell me what is correct way to adding these two methods, to my existing project.
![error](https://cloud.githubusercontent.com/assets/26266949/25116972/8e3ab844-242d-11e7-9426-c918ed966190.png)

the above screenshot is a part of my access controller. if I change the word default into expenses , all works fine.  why is that

**Comment by ch-gz** [comment]
@shameera91 I just noticed that Expenses module is the same level as Default module. So you need to make it like this "$acl->addResource(new Zend_Acl_Resource('**expenses:expenses**'));
                    $acl->allow('admin', 'expenses:expenses', array('index','edit','clone','view','delete','addpopup','uploadsave','uploaddelete','displayreceipts','addtrippopup','submitexpense','addreceiptimage','expensestatus','listreportingmangers','viewmoremanagers','forwardexpenseto','downloadexpensepdf','bulkexpenses','getcategories','getprojects','getcurrency','uploadedfiles'));"

**Comment by nadhir2** [comment]
Hi, 

I have the same problem can't add expenses... Can anybody help me to solve this matter
