### ISSUE TITLE
Super Admin cannot access "Assets Category"

### ISSUE THREAD

**Issue by 4poorv** [sapplica/sentrifugo#132]
**Steps to Reproduce:**

1. Sentrifugo 3.1 
2. Login with superadmin credentials.
3. _Menu  > Assets > Assets Categories_ 

It doesn't allow superadmin user to access the page:

![asset_category_not_authorized](https://cloud.githubusercontent.com/assets/13313876/25126265/5819795e-244f-11e7-9738-d26b4f1a6010.png)

Even when we try to add it another way as :
_Assets > Add > Category (Dropdown) > Add Category_
It won't allow super admin.

![asscatpop](https://cloud.githubusercontent.com/assets/13313876/25126365/ae235d92-244f-11e7-9d65-121bf4a00cc9.png)

**Comment by shameera91** [comment]
hello 4poorv,
 Do u update your roles and privileges for any role? 
Sometimes it solves your problem

**Comment by 4poorv** [comment]
@shameera91 I didn't understand!! we cannot modify _"Roles & Privileges"_ for **Super Admin.**
The **Super Admin** is not included in the organization’s employees’ list.

**Comment by shameera91** [comment]
goto  
 HR->user management -> roles and privilages
click edit, for any role in the list
then click update

**Comment by 4poorv** [comment]
Cleared browsing data (chrome) including cookies and tried. The problem isn't there anymore.
@shameera91 Thanks for the suggestion, I'll keep it in mind. Incase issue occurs in future.

**Comment by faisaljanjua** [comment]
I got the same issue, Install fresh copy but still it same.
HR have full rights but under Assets, its showing restrict sign.

How can I add children under dependency tab?
An Employee have 4 children, usually after add 1 child, option remove from dropdown.

**Comment by gururajahegde** [comment]
@faisaljanjua 
For 2nd problem check patch
https://github.com/sapplica/sentrifugo/compare/master...gururajahegde:patch_3.2_1

Mother is added as dependent in above patch, in similar way Add child1, child2, child3, child4 in /application/modules/default/forms/Dependencydetails.php file.
Note: Don't forget to apply changes to /application/modules/default/models/Dependencydetails.php as it is in patch.
