### ISSUE TITLE
How to change superuser password from database

### ISSUE THREAD

**Issue by RayvatBPOservices** [sapplica/sentrifugo#134]
I want to change the super user password and email. 

I don't know the previous super user password so i can't login into panel. 

So how can i reset password and email using database?

**Comment by 4poorv** [comment]
1st thing to note here is, the password stored in the database will be encrypted (Obviously). So if your password is **"qwerty123"**, it will look like this -> **"3fc0a7acf087f549ac2b266baf94b8b1"**. Just browse the table **"main_users"** in the DB (maybe using a GUI tool like PHPMyAdmin), You'll see all users details but the passwords will be in encrypted form.

Now, if **you want to RESET super admin password**: 

1. **If you have access to current super admin email** then u would probably just click **forgot password** link and get an email with the new password (Easy..)

2.  **If you cannot access super admin email** (Presuming you are not playing with production) : 
Now you know that the password **"qwerty123"** gets encrypted like this **"3fc0a7acf087f549ac2b266baf94b8b1"** in DB, Let say you want to change password for a user named **"**Tiger**"**

**a.** Access **"main_users"** table in the DB.
**b.** Edit email fo user "**Tiger**" if you want. i.e **tiger@example.com**
**c.** Set password for user "**Tiger**" to this exactly -> **"3fc0a7acf087f549ac2b266baf94b8b1"**
**d.** Now you should be able to access your tiger using those credentials:
      email : **tiger@example.com**
      pass :  **qwerty123**

Hope you find it helpful :)

**Comment by ch-gz** [comment]
Run the query as below:
Query: update main_users set emppassword=md5('example') where id=1;
So the new password for user id=1 is "example"

**Comment by gautham1429** [comment]
Can you please tell me, what you are mentioning that md5('example') . Is that username or anything else @ch-gz

**Comment by ch-gz** [comment]
@gautham1429 md5('type your new password here'), this is your new password for specific user in the table.

**Comment by gautham1429** [comment]
Is sentrifugo 3.3.3 version is supported in Windows 10 ???

**Comment by FifalianaHariniasy** [comment]
thank you :) it works
