### ISSUE TITLE
Calendar view switch to start from Monday

### ISSUE THREAD

**Issue by klukiyan** [sapplica/sentrifugo#135]
Hi,
We would need that employees see european calendar style when applying for leaves. So the week starts from Monday, not from Sunday.
I couldn't find in settings, and in the code I got completely lost.
Is there any way to switch it? If it's not available, can you at least point me in the right direction. For me just fully switching to Mon-Sun week would work. Maybe enough to update database week values? :)
Thank you

**Comment by klukiyan** [comment]
firstDay: 0 to firstDay: 1
closing thank you :)

**Comment by jaccab** [comment]
I have the same problem, I would like to have the calendar staring on Monday.
Could you help me please?

**Comment by klukiyan** [comment]
@jaccab 
In your editor's global search (CTRL+SHIFT+F) look for `firstDay: 0` and replace it with `firstDay: 1`.
The most important is here: `public\media\jquery\js\fullcalendar.js`. `line:63` It will change the big calendar, and possibly small ones. But if you change them all, then you will be sure that no part of the interface gives you sunday as first day :)

same way you can add the week numbers if you want

![image](https://user-images.githubusercontent.com/27725051/51479412-6d6e0880-1d8e-11e9-9f9a-2f2e0e432168.png)

![image](https://user-images.githubusercontent.com/27725051/51479445-84acf600-1d8e-11e9-813c-78724624b339.png)

**Comment by jaccab** [comment]
I thought I could change it directly into the database. I'm not a developer :( and you're talking about edit the code with a tool like vscode and search and replace those values , isn't it? thanks!

**Comment by klukiyan** [comment]
@jaccab 
that's correct. and yes vscode does it perfectly :)
You can try to edit at least 1 file that I've mentioned. It will fix the calendar in most of the places.
If you need to make many considerable changes, feel free to hire me. I've made very heavy changes and fixes to this tool to adapt it to one huge company.

**Comment by jaccab** [comment]
I replaced all the files with firstDay: 1 but I'm not able to public this new version since vscode. I suppose I have to debug the application again but It doesn't work, when I press F5 the following message appears. "Cannot find runtime 'node' on PATH. Is 'node' installed? 
File launch.json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "program": "${workspaceFolder}/Sentrifugo\\public\\media\\jquery\\js\\fullcalendar.js"
        }
    ]
}
Note: the software is installed into a server with a partition D

**Comment by klukiyan** [comment]
@jaccab ,
You don't need to debug it in VScode. No need to press F5. You just need to get the updated files to the server. There are several ways to do it.
1. Simplest way is to copy paste them (with overwrite) from your computer to server via some FTP client (Filezila). You can make a zip of only modified files. Or you can entirely copy paste their parent folder including all contents to FTP. Refresh page, and everything works.
This is the most newbie-friendly approach. It's simple, but it's not simple if you will be doing it again and again often. And it doesn't give you backup possibility.

2. More complicated way is installing some "SFTP Simple" extension and have them automatically FTPed to server whenever you press CTRL+S.
3. most complicated, but best safest and fastest is the Git deployment

**Comment by jaccab** [comment]
But I updated those files with vscode directly into the server folder because I didn't have a local version copied into my computer.
I have now these files fullcalendar.js, jquery-ui.js and jquery-ui-1.10.3.custom.js all with firstday:1 as you indicated into this folder D:\xampp\htdocs\Sentrifugo\public\media\jquery\js and the calendar continue as SUN first day :(

**Comment by klukiyan** [comment]
@jaccab 
1. restart xampp server 
2. refresh the browser page. Preferably with SFIFT+F5 to avoic cashed js possibility
3. make sure that you have firstDay, not firsday. Javascript is super case sensitive. No excuses

**Comment by jaccab** [comment]
Now it Works!!! Thank you very much for your help.

**Comment by jaccab** [comment]
Is it possible to export or print in PDF the views Organization Structure and Organization Hierarchy?
