### ISSUE TITLE
add custom sql-query report to analytics

### ISSUE THREAD

**Issue by klukiyan** [sapplica/sentrifugo#138]
It's very amazing tool. I need to customize it slightly to fit our needs. Into analytics I need a custom sql query report. Doesn't have to be super user friendly with filters. Doesn't have to be excel. csv would suffice.
whereever I add the php sql query, it starts giving me errors. Please give me a hint how can I add a custom sql query report. for example select * from main_users to csv by user's button click in analytics

**Comment by ch-gz** [comment]
I think you need to modify related models and controllers to do that.
