### ISSUE TITLE
Report Export to Excel doesn't work in internet explorer

### ISSUE THREAD

**Issue by klukiyan** [sapplica/sentrifugo#147]
Hi,

For some reason "Export to Excel" from analytics works perfectly in chrome, but doesn't do absolutely anything when trying to click in excel. The cursor changes shape showing that it's clickable, but absolutely nothing happens. Tried to check the security, trusted sites, pop-up blocker to be disabled, nothing helps. Export to Excel or Export to PDF buttons don't react at all

**Comment by sapplica** [comment]
Hi,
Kindly elaborate your query and send us supporting screenshots, so that we can understand your query better. Thank you.

**Comment by klukiyan** [comment]
Hi I literally explained exactly what happens. I've also read on internet, that it's some problem with Internet Explorer 11 (64 bit) in particular. The "Export to Excel" works well in Chrome, Firefox, old Explorer, Edge but it doesn't do literally anything when you click on it in Internet Explorer 11.

**Comment by sundayayandele** [comment]
@klukiyan, what is your operating system and i think it would work on Windows10 Internet explorer. Just give it a trial.

**Comment by klukiyan** [comment]
@sundayayandele 
oh I resolved this such a long time ago. most users have only internet explorer and win 7, and it didn't work because browser doesn't support such elements. I recoded them long time ago and it works nice :)
forgot to close the issue

**Comment by sundayayandele** [comment]
Export employee report in Excel is showing error below:
http://xxxx.com/xxx/index.php/default/reports/exportemployeereport?reporting_manager=&emprole=&jobtitle_id=&position_id=&emp_status_id=&date_of_joining=&modeofentry=&page_no=1&per_page=20&sort_name=modifieddate&sort_type=DESC&cols_arr%5BemployeeId%5D=Employee+ID&cols_arr%5Buserfullname%5D=Employee&cols_arr%5Bemailaddress%5D=Email&cols_arr%5Bcontactnumber%5D=Mobile&cols_arr%5Bemprole_name%5D=Role&cols_arr%5Breporting_manager_name%5D=Reporting+Manager&cols_arr%5Bjobtitle_name%5D=Job+Title&cols_arr%5Bbusinessunit_name%5D=Business+Unit&cols_arr%5Bdepartment_name%5D=Department might be temporarily down or it may have moved permanently to a new web address.
ERR_INVALID_RESPONSE

**Comment by sundayayandele** [comment]
@klukiyan, can you assist with the error above

**Comment by klukiyan** [comment]
@sundayayandele this issue has been closed long time ago. why do you keep posting new issues here?
[how to create a new issue](https://help.github.com/articles/creating-an-issue/)
