### ISSUE TITLE
New feature: add ability to export employees list

### ISSUE THREAD

**Issue by schlos** [sapplica/sentrifugo#15]
Currently in /index.php/employee/ screen, there is ability to import employees:

Home › Human Resource › Employees
Import Employees and Import format

Would be also very nice to have option to export existing employees in same format as seen in "Import format".

**Comment by sapplica** [comment]
Hi,
We do have the export feature in Sentrifugo. 
Please follow the below path:

Home > Analytics > Employees > Employees

There are 3 ways to export employee data:
1.Directly click on 'Export to PDF' or 'Export to Excel' on the right side of the screen. This will produce a default report as displayed in the grid. 

2.Click on the orange drop down button next to the heading Employees in the grid. On clicking it, you will see a number of check-boxes which will help you to customize how you want to view your report.(After selecting the check-boxes, you can click on 'Apply'). Now, you can export it to PDF or Excel.

3.On the left side of the screen, there is another section 'Generate Custom Report'. Through this option, you can generate a report specific to a condition and then you can export the data . Example: Only the employees belonging to a specific business unit. 

Regards,
Team Sentrifugo

**Comment by schlos** [comment]
Thank you.
I can confirm that export option is there. I have missed it earlier, sorry.

**Comment by vertokite** [comment]
Hello
I see that there is the possibility to export employee data.  However, can I also export  "leave" data for our external accounting department to prepare the payrole documents?
Thanks

**Comment by thierryotis** [comment]
I'm using Sentrifugo 3.2 and I can't see that feature or may be my employees icon on reports can't be clicked.

**Comment by faisal78676** [comment]
I am not able to view employee list in analytics even in sentrifugo demo lin. please help me to sort this issue.
