### ISSUE TITLE
Different Weekend Days same Department

### ISSUE THREAD

**Issue by payaso99** [sapplica/sentrifugo#161]
Weekend day 1 is set to Saturday
Weekend day 2 is set to Sunday

Employee1 has a regular weekend of Saturday and Sunday
Employee2 has different day off like Monday and Tuesday

They are on the same department. 

If employee2 is requesting for a leave on a Saturday or Sunday it gives an error:
**You cannot apply leave on Weekend/Holidays.**

How do we do that since many employees have a different weekend days?

Thanks,
Payaso

**Comment by klukiyan** [comment]
Hi @payaso99 , 
just put them into different departments and set one department to have weekend on SatSun and the other department to MonTue.
In regards to vacation approval manager, just set the manager to "Management" role-> in that case you will be able to have the employee from other department report to that manager without any problems.

**Comment by payaso99** [comment]
ok so I will be needing more departments. Thanks klukiyan.

**Comment by juanykty** [comment]
> I solved this problem commenting this lines on the file /var/www/html/Sentrifugo/application/modules/default/forms/leavemanagement.php
> ```
>                 $weekend_startday = new Zend_Form_Element_Select('weekend_startday');
>         $weekend_startday->setRegisterInArrayValidator(false);
>                 $weekend_startday->addMultiOption('','Select Weekend Start Day');
> #        $weekend_startday->setRequired(true);
> #               $weekend_startday->addValidator('NotEmpty', false, array('messages' => 'Please select weekend day 1.'));
> 
>                 $weekend_endday = new Zend_Form_Element_Select('weekend_endday');
>         $weekend_endday->setRegisterInArrayValidator(false);
>                 $weekend_endday->addMultiOption('','Select Weekend End Day');
> #        $weekend_endday->setRequired(true);
> #               $weekend_endday->addValidator('NotEmpty', false, array('messages' => 'Please select weekend day 2.'));
> ```
this solution don't work


antoher solution that I try are modify the database 
SELECT * FROM `main_weekdays`
and add this lines 
![sql](https://user-images.githubusercontent.com/30271703/37168449-2644d82a-22c2-11e8-9cbd-8ae153af00de.JPG)
and put the day's 0 and 1 of weekend
