### ISSUE TITLE
Big calendar info for managers

### ISSUE THREAD

**Issue by klukiyan** [sapplica/sentrifugo#178]
Hi,
When the manager selects "Employees reporting to me" he can see the leaves of subordinates on the calendar, in this format:
Employee Name, Leave, (A)
Please, suggest me, where is the code that controls this line. I want to change the "Leave" word to be changed to respective leave type.
Which is the file that contains the code the builds these lines please?

**Comment by sapplica** [comment]
Hi,

You can change the code in 'LeaverequestController.php' and the view in 'index.phtml' files.

File Path:  \...(application location...)\...(application name)...\application\modules\default\controllers

 \...(application location...)\...(application name)...\application\modules\default\views\scripts\leaverequest\index.phtml

**Comment by klukiyan** [comment]
@sapplica , thank, found it :)
very nice.
## thank you for your help.
