### ISSUE TITLE
Modify email layout

### ISSUE THREAD

**Issue by dean-github** [sapplica/sentrifugo#181]
Hi team,
I couldn't find a place to modify the email layout for notification where I can add more static information to the content of the email.
Could you please let me know how to modify it or where I can find the function for that?
Thanks

**Comment by klukiyan** [comment]
Hi @dean-github ,
Which emails you want to modify?
There are:
* Welcome emails with credentials
* Leave approvals/requests/confirmation emails
If you want to modify the content of the leave approvals/requests emails, then these are spread within these 3 files:
> .\application\modules\default\controllers\LeaverequestController.php
> .\application\modules\default\controllers\ManageremployeevacationsController.php
> .\application\modules\default\controllers\PendingleavesController.php

you'll find it by context in html. you can add not only static text, but also dynamic text using $variables

**Comment by dean-github** [comment]
Thanks Kiril,
I'd like to change layout for all email like forgot password, welcome
email... so that the email better reflect our company custom.
Now I'm testing sentrifugo and every time my colleagues received an email
they thought kind of spam emails until I told them that's from me.
Are all email templates in application\modules\defaults\controllers folders?
Thanks

On Aug 30, 2017 05:24, "Kiril Lukiyan" <notifications@github.com> wrote:

Hi @dean-github <https://github.com/dean-github> ,
Which emails you want to modify?
There are:

   - Welcome emails with credentials
   - Leave approvals/requests/confirmation emails
   If you want to modify the content of the leave approvals/requests
   emails, then these are spread within these 3 files:

.\application\modules\default\controllers\LeaverequestController.php
.\application\modules\default\controllers\ManageremployeevacationsContro
ller.php
.\application\modules\default\controllers\PendingleavesController.php

you'll find it by context in html. you can add not only static text, but
also dynamic text using $variables

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/sapplica/sentrifugo/issues/181#issuecomment-325808783>,
or mute the thread

**Comment by klukiyan** [comment]
@dean-github ,
No, the welcome email and password reset emails are located in different locations. 
I suggest you start by installing vscode or sublime text. You can do mass search through all files at once. This way you'll be able to find almost everything. 
You'll need to know a bit of php, js, html to properly adapt sentrifugo to your organization's needs. And it really requires a lot of adapting. It could be great in the result, but it would require very large time investment until it gets brought to perfection

**Comment by dean-github** [comment]
Thanks for your advice. It's clear to me now.
Have a nice day!
Best regards,

**Comment by sshakyawar** [comment]
Hi, 

I am new to setrifugo HRMS, I want to modify the email header, message and content, where I can find the template for welcome message?

TIA

**Comment by klukiyan** [comment]
@sshakyawar  read above. all message template file locations are mentioned in this thread already

**Comment by sshakyawar** [comment]
Thanks !! I got the issue resolved.
I want to implement my own payroll and attendance module for the HRMS.
How can I go about this? any help or hint will be appreciated.
TIA

**Comment by klukiyan** [comment]
@sshakyawar oh man, that would be not easy at all. you'll need to understand php, be familiar with MVC and Zend framework.

**Comment by sundayayandele** [comment]
where do we install the vscode or sublime tex into?

**Comment by klukiyan** [comment]
@sundayayandele , [vscode](https://code.visualstudio.com/) and sublime text are just powerfull text editors for developers using which it's relatively easy to add extra features to Sentrifugo or any other web application.  
**To have it "relatively easy" you need some skills with PHP, js, and MVC.**. For example adding some extra dropdown to leaverequest form would mean:
1. edit the controller `leaverequestcontroller.php`
2. edit the form in forms `leaverequest.php`
3. edit the MODEL `leaverequest.php`
4. edit the view `leaverequest/index.phtml`
5. add respective column to mysql db

of course you cannot do these with some notepad. You'll need some powerful editor like  [vscode](https://code.visualstudio.com/)  and preferably git.

**Comment by sundayayandele** [comment]
@klukiyan, thanks your advice was helpful. I was able to edit the notification mail.
I will appreciate if you can provide similar guidance as to the files to edit in order to add the 2018 leave calender to the Sentrifugo so that users can apply for it in 2017.

Also i would need your guidance to how "Alloted leave year" an input field or make it editable 

![image](https://user-images.githubusercontent.com/20027133/33367207-14de0f06-d4ee-11e7-9509-0ae2e002de04.png)

**Comment by sundayayandele** [comment]
@klukiyan , i want to be able to make the "Alloted Year" an input or editable file, please which php code will i need to edit to achieve this?

**Comment by klukiyan** [comment]
@sundayayandele , making is editable is very simple. But it will not help you. Sentrifugo doesn't have the code to properly support future year. 
If you allot leaves for 2018 now, employees will not be able to "use" them anyway. Because all sentrifugo's scripts use "current year" ```date("Y")``` across the controllers and jqueries.
So you have 3 ways to resolve it:  
1) update controllers and jqueries that currently prevent employees from taking the 2018 holidays and allot the 2018 entitlements to 2017. The remaining of them will automatically become 2018 at the begining of the year. If they don't, you can mass-update via sql
2) update more controllers and jqueries and MODELS (more than 10 different files with code) to make sentrifugo properly handle future years as it should be.
3) hire somebody to do it for you. (not me. I can do it, but I'm very busy till Jan 2018)

**Comment by sundayayandele** [comment]
@klukiyan, thanks for your response. I would appreciate assuming you have done it before to send the lsit of the names/list of controllers and jqueries that i need to update.

I am very good with mysql and i would appreciate if you have the mass-update sql template i can use.

Also if you dont mind identifying all the 10-different files with code that i need to update so that it can handle future years.

**Comment by klukiyan** [comment]
@sundayayandele ,
For me the solution number 1 was enough.

**Comment by sundayayandele** [comment]
@klukiyan , Thanks for your response. I would appreciate if you can specify the list of the specific controllers  path and jqueries names that you used when you did yours.

**Comment by sshakyawar** [comment]
@klukiyan thanks for the suggestions. It will be great if you can define in which list of controllers and files we have to change to edit the 2017 year to future year.

**Comment by nando2601** [comment]
Hi... i want change the template header login form sentrifugo,,, can you help me?

**Comment by vincentndl** [comment]
> 
> 
> Hi @dean-github ,
> Which emails you want to modify?
> There are:
> 
>     * Welcome emails with credentials
> 
>     * Leave approvals/requests/confirmation emails
>       If you want to modify the content of the leave approvals/requests emails, then these are spread within these 3 files:
> 
> 
> > .\application\modules\default\controllers\LeaverequestController.php
> > .\application\modules\default\controllers\ManageremployeevacationsController.php
> > .\application\modules\default\controllers\PendingleavesController.php
> 
> you'll find it by context in html. you can add not only static text, but also dynamic text using $variables

Hello bro!
When I create a new user and update my email, the login account will be sent to the email entered, but I want to change the "Greetings from Sentrifugo" content, how do I do it?
Best regards

**Comment by klukiyan** [comment]
@vincentndl 
I surely found how to do it. Becasue the email from tool are customized (see below screenshots)
But it's been 3 years ago. i don't remember how and I don't have time to dig the zend code to find out how.

To be honest today, I wouldn't use this tool. It's so old and outdated, and adapting it to become a real system took my so much time back then, that I would rather wrote it from scratch using some modern techologies. I would suggest **laravel** backend and **Nuxtjs** frontend

![image](https://user-images.githubusercontent.com/27725051/79853557-823daf80-83c8-11ea-90c4-8a0648dc87de.png)

![image](https://user-images.githubusercontent.com/27725051/79853573-85d13680-83c8-11ea-86d7-b160afeaa464.png)

**Comment by vincentndl** [comment]
> I surely found how to do it. Becasue the email from tool are customized (see below screenshots)
> But it's been 3 years ago. i don't remember how and I don't have time to dig the zend code to find out how.
> 
> To be honest today, I wouldn't use this tool. It's so old and outdated, and adapting it to become a real system took my so much time back then, that I would rather wrote it from scratch using some modern techologies. I would suggest **laravel** backend and **Nuxtjs** frontend

Tks @klukiyan!

I'm just starting to learn, I'm not a programmer, I'm just a sysadmin and I find it quite responsive to the basic needs of my company, you can suggest or remember where to change. Can you change it? Currently, it is almost completed but there are 2 error issues: the number of days of the calculation error and the popup when clicking the leave type link.
For example: taking leave from 01 - 03 total is 3 days but the software only counts 2 days.
Thank you very much, hope you will help me or suggest me to use any software similar to this.

**Comment by ShuchiSaraiya** [comment]
time sheet weekly reminder mail is not working. please suggest something.
greetings.
