### ISSUE TITLE
Major issue with leave approval pop-up.

### ISSUE THREAD

**Issue by klukiyan** [sapplica/sentrifugo#183]
Hi @sapplica ,

Today I've encountered a big issue in [LeaverequestController.php](https://github.com/sapplica/sentrifugo/blob/master/application/modules/default/controllers/LeaverequestController.php)
https://github.com/sapplica/sentrifugo/blob/0ddb8c1422fb5ab834c84fc1dd4282f2727d6d2b/application/modules/default/controllers/LeaverequestController.php#L951

I don't know how it works, but it looks like the query behind it doesn't look by ID.
It worked nice until I had to add some back-end records manually for few maternity leaves employees.
So I ended up skipping 2 **id** fields. 
Thus, when I click the 3 dots (...) for the pop-up window to approve the vacation, let's say vacation id 907, I end up approving the one with id 905. Always 2 id's back. 
The eye icon approval works ok, as it has correct and direct link. However the line 951 that I've mentioned brings up the wrong ID and ruins everything.

I've temporarily disabled the 3dots pop up approval from "grid", but I need a solution for this "getparam" from #L951. It needs to bring the right vacation by ID, not by rowcount :(
Thank you

I think I have a guess. But I can't believe it can be true.
Can it be that the GetParam('id') takes it from **_main_leaverequest_summary_** instead of _**main_leaverequest**_ ?! Seriously? Opening with one table and then bringing in data from another?
https://github.com/sapplica/sentrifugo/blob/0ddb8c1422fb5ab834c84fc1dd4282f2727d6d2b/application/modules/default/controllers/LeaverequestController.php#L951

**Update:** I've resolved the issue. I ended up having an id discrepancy in **_main_leaverequest_summary_** between **id** field and **leaverequest_id** fields.
It's weird however that when querying the leave details from **_main_leaverequest_summary_**, the **id** field is being used instead of **leaverequest_id**...

**Comment by klukiyan** [comment]
please somebody help me understand how it functions. why the retrurned $id is wrong? :(
I need to find a solution. what is the logic behind this "getparam()", why it displays on pop-up the right data, but then sends wrong data to query :(

**Comment by sapplica** [comment]
Hi,

We are using triggers, so that's the reason you will see two tables and 'main_leaverequest_summary' is for analytics. Thank you!

**Comment by klukiyan** [comment]
Hi @sapplica ,
I know, I even "upgraded" some of the triggers to populate the additional tables that show leaves not only **1 leave per line** but also **1 line per each day of leave**.
The issue I had is that I had to add some extra leaves via backend to **main_leaverequest**, it then triggered well into **main_leaverequest_summary**. However when a new leave was requested, the new ID in **main_leaverequest** skipped one number _(don't know why)_. As result in **main_leaverequest_summary** the **id** field was left behind **leaverequest_id** field. It was 1 step back. So the pop-up approval/cancel/reject functionality got broken.
I've fixed it by equalizing them again in **main_leaverequest_summary** and all is good now.
Thank you
