### ISSUE TITLE
Multiple Business Unit under 1 management Head

### ISSUE THREAD

**Issue by syedniz** [sapplica/sentrifugo#184]
Hi,

I like to know if there is a way to make single management head or manager as reporting manager for multiple business unit departments.

Thanks,
Syed Nizamdheen.

**Comment by sapplica** [comment]
Hi,

Kindly elaborate more, to help us understand your query better. Thank you!

**Comment by klukiyan** [comment]
Hi @syedniz ,  
This aspect is managed by "Employee Role".  
Only ones that have role "Management" have the possibility to have reports from multiple business units or multiple departments.  
Also only users with "Management" role can be "promoted" to become org head. 
So your solution would be quite simple. Each team-leader/manager that needs to have direct reports from multiple departments will need to be updated to **Management** role. That's it.
_Don't forget to also go to HR>Employee Management>Roles&Priveleges and make sure that you've given correct permissions for each role_

fyi @sapplica

**Comment by syedniz** [comment]
Hi @klukiyan,
Thank you for the solution it worked after moving the managers to Management role.
Thanks again,
Syed Nizamdheen.
