### ISSUE TITLE
superadmin credentials are not accepted after logout or session is closed

### ISSUE THREAD

**Issue by dmsherazi** [sapplica/sentrifugo#20]
I just installed Sentrifugo  and finished configuration wizard. I got the system generated password for EMPP0001 and used it to login. 

After the session got expired it is not accepting the password. 

I didn't update the email so I cant get forgot password email. 

How to solve this. It is second installation and have the same issue. 

How can i decode the password from db?

**Comment by sapplica** [comment]
Hi,

When you click on 'Forgot Password' the new password is sent to the Super Admin's email i.e. the email you had used to install Sentrifugo. Kindly check that email id and let us know if you got the mail.

Regards,
Team Sentrifugo

**Comment by dmsherazi** [comment]
using  the email instead of Employee number in the username/email feildsolved the issue

**Comment by shivaspk** [comment]
This really is little odd, I encountered the same issue today and only emailID instead of EMPP0001 worked.

**Comment by AbhishekAggarwal** [comment]
Same thing was happening to me as well. But, In my case, the server disk space was full. I just removed the unwanted files and all set to normal.
