### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by benargo** [sapplica/sentrifugo#24]
Hi there,

We're getting an error in Step 3 ('Application Settings') of the installer. Its passed steps one and two but when submitting the form its returning the message "Some error,please try again."

![Screenshot](https://s3.amazonaws.com/f.cl.ly/items/3T3R001k3D1v0K1p2e1X/Sentrifugo%202016-02-23%2023-42-18.png?v=f6c70835)

The nginx log files are reporting the following:

`2016/02/22 23:59:27 [error] 2621#0: *389 FastCGI sent in stderr: "PHP message: PHP Warning:  require_once(step.php): failed to open stream: No such file or directory in /var/www/example.com/install/index.php on line 144
PHP message: PHP Fatal error:  require_once(): Failed opening required 'step.php' (include_path=':.:/usr/share/php:/usr/share/pear') in /var/www/example.com/install/index.php on line 144" while reading upstream, client: 86.31.184.155, server: example.com, request: "GET /install/index.php?s=p HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "example.com"`

Any thoughts on this would be greatly appreciated. Please let me know if you need any additional information.

**Comment by sapplica** [comment]
Hi,

We apologize for the delay. Were you able to resolve the issue?

**Comment by azizarnold** [comment]
I'm getting the same issue at same place.

**Comment by benargo** [comment]
We ended up moving away from Sentrifugo. I'm going to close the issue as we weren't able to find a resolution. @azizarnold, feel free to open a new issue if you're still affected.

**Comment by Arjoni** [comment]
Does it work on nginx? Can you please share the vhost config file? I have tried everything but it's still not working...

**Comment by arasub** [comment]
Now with Sentrifugo 3.1.1 works with Nginx and php 5.6
