### ISSUE TITLE
icons are not getting dispalyed in configuration screen

### ISSUE THREAD

**Issue by nagendra-prasad** [sapplica/sentrifugo#25]
Hi Team,
i was able to install and configure sentrifugo 2.1 successfully but when i open the page it shows loading but nothing happens
![loading error](https://cloud.githubusercontent.com/assets/17737157/13626231/05f1d6c4-e5e6-11e5-965f-3b7780e97427.png)

**Comment by sapplica** [comment]
Hi,

We've replied to your email. Kindly check.Thanks!
