### ISSUE TITLE
Hosting sentrigufo on my godaddy linux server

### ISSUE THREAD

**Issue by Shaunzy** [sapplica/sentrifugo#272]
I am facing issue while Hosting sentrigufo on my godaddy linux server
i have created subdomain, and in that subdomain i want to host sentrifugo

but i am receiving this error - "Some error occured. SQLSTATE[28000] [1045] Access denied for user 'root'@'ip-160-153-18-103.ip.secureserver.net' (using password: NO)"

![sentrifugo error](https://user-images.githubusercontent.com/41664255/44580740-b490a700-a7b8-11e8-885d-8ba7209f952b.PNG)

**Comment by phinguyen** [comment]
use localhost instead of domain

**Comment by Shaunzy** [comment]
Tried that too, same error...

**Comment by phinguyen** [comment]
are you sure about other information, like user/password - you can try by use this code: https://gist.github.com/chales/11359952

**Comment by Shaunzy** [comment]
Thanks, this helped.
