### ISSUE TITLE
FORGOT PASSWORD NOT WORKING 

### ISSUE THREAD

**Issue by shainkykumar** [sapplica/sentrifugo#314]
hye ,
       I am  not receiving any email when we use the option "forgot password " to reset existing password through mail ....

**Comment by shainkykumar** [comment]
it is working now .... after deployment

**Comment by xfeo** [comment]
Hello,

I am experiencing a similar issue with "**Sentrifo V3.2**"; the Setrifugo server email works properly for everything except for the user password recover... No email is sent by "Forgot Password".

What can I do to recover the user password?

Thanks in advance,

Kind Regards.
