### ISSUE TITLE
Make MySQL Port Configurable.

### ISSUE THREAD

**Issue by CarBee** [sapplica/sentrifugo#33]
Please update the source to provide configuration for MySQL Port if the port is other than 3306.

Thanks
Thangaraj N

**Comment by sapplica** [comment]
Hi,

Kindly elaborate your query, so that we can understand your request better. Thanks!

**Comment by CarBee** [comment]
We are using port 3307 instead of standard port 3306 for MySQL. We need
this to be configurable so that any different port other than 3307 should
work fine with Sentrifugo.

Thanks
Thangaraj N

**Comment by CarBee** [comment]
Need to include the Port as part of ServerName

ServerName:PortName
