### ISSUE TITLE
Issue in time sheet

### ISSUE THREAD

**Issue by AruljothySundaramoorthy** [sapplica/sentrifugo#331]
Unable to enter time in the timesheet. it was showing no project was assigned.

please help me to resolve this issue.

**Comment by BigOreo** [comment]
Make sure you first assign a project and a task. If you are missing these two items together then you will not have them show up in your timesheet.

**Comment by AruljothySundaramoorthy** [comment]
Yes, it's working fine....Thanks :)

**Comment by AruljothySundaramoorthy** [comment]
The above comment was working hence closing this issue
