### ISSUE TITLE
Adding custom fields to the application

### ISSUE THREAD

**Issue by SiNONiMiTY** [sapplica/sentrifugo#36]
Hi,

I would like to add custom fields to the application. For example, I want to add an additional `Middle Name` field on the employee details. I already added the necessary columns to the database. 

What I'm looking for now is, what Models and Controllers should be modified? I was already able to edit the views and show the textbox fields that I want to show. The next step is to populate those fields with data from the database. I'm fairly new in using Zend Framework, so, I'll be needing guidance in doing this.

EDIT:

I was able to find the necessary files to be edited, closing this issue.

**Comment by Mayesoo** [comment]
Misakachi! ! Your issue is closed, would you please tell us the files that can be edited. Thanks

**Comment by MiSAKACHi** [comment]
Hi, do you still need help? Are you familiar with the Zend Framework?

PS: Sentrifugo 3 is now released, you may want to take a look at it as it might have the features that you are looking for.

**Comment by asiandoll** [comment]
I need help with this can you tell me what to do please?

**Comment by thierryotis** [comment]
Hello! Really need to know how to add custom fields! Thanks.

**Comment by shahanad4u** [comment]
I need help with this can you tell me what to do please?

**Comment by vara1234** [comment]
I have added close to 50 new custom fields and implemented the product successfully . It is possible to customize product the way we need , you can reach me on varapraveen@gmail.com for any info

**Comment by vara1234** [comment]
I have added close to 50 new custom fields and implemented the product  Sentrifugo successfully . It is possible to customize product the way we need , you can reach me on varapraveen@gmail.com for any info
