### ISSUE TITLE
Unable to import employees

### ISSUE THREAD

**Issue by SiNONiMiTY** [sapplica/sentrifugo#38]
Unable to import employees. I followed all the instructions provided on the import page. After correcting all the errors, I was presented with a vague error message 'Something went wrong,please try again'.

I also tried importing the provided file format, I just changed some of the sample values and yet, same error message popped out.

If there is no way to import employees via the import interface, can I manually import them on the database?

**Comment by sapplica** [comment]
Hi,
Are you facing this issue while adding employees one at a time? Kindly ensure the following:
-Use the correct short codes assigned for various fields.
-Do not change the order of the columns or delete columns in the import sheet

**Comment by SiNONiMiTY** [comment]
`Are you facing this issue while adding employees one at a time?`
- By adding at the Add Employees section? No. Adding one at a time has no problem.

`Use the correct short codes assigned for various fields`
- I'm pretty sure I have used all the correct codes as I have intentionally set them to wrong ones and the system reported an error. (e.g. Invalid Dept Code)

`Do not change the order of the columns or delete columns in the import sheet`
- I followed the format provided, no extra or removed columns. I just filled them out



Thanks for the assistance.

**Comment by sapplica** [comment]
Hi,

Please click on the button 'Import Employees' and then send us your apache logs. Kindly email them to us at support@sentrifugo.com. Thank you!

**Comment by SiNONiMiTY** [comment]
Hi,

Thank you for your response. I found the problem:

![snip](https://cloud.githubusercontent.com/assets/9588282/16759761/14ebfe62-484b-11e6-84ba-79562e31d3a0.png)

According to the Import Guide, salary is not mandatory so I skipped that field. Filling up that field solved the problem.

Once again, thank you for providing assistance. Have a nice day ahead.
