### ISSUE TITLE
Issue in Work Eligibility Module

### ISSUE THREAD

**Issue by MiSAKACHi** [sapplica/sentrifugo#40]
Adding new Work Eligibility details calls the editAction of the controller instead of the addAction of the workeligibilitycontroller, thus, leading to a 503 error being thrown by the application when adding a new detail.

**Comment by sapplica** [comment]
Hi,

Kindly perform the action that leads to the error and then send us your apache error logs to support@sentrifugo.com

Regards,
Team Sentrifugo

**Comment by MiSAKACHi** [comment]
**Prior to performing the said action, I performed the following steps**
> Logged out of the application
> Cleared the Apache Error logs

**Then, to reproduce the error, these steps were taken**
> Logged in to the application as the Super Admin
> Navigated to HR->Employees->Edit->WorkEligibility
> Filled in the necessary fields
> Pressed Save
> 503 Error appears

**The Screen Cap**
>>
![scap](https://cloud.githubusercontent.com/assets/9588282/17049318/30e2d1c8-501f-11e6-9429-52717b7ac888.png)

The Apache error log was sent with to the provided mail address.
