### ISSUE TITLE
Server Health software needed

### ISSUE THREAD

**Issue by Stef1337** [sapplica/sentrifugo#42]
Would recommend some good software that could help in protection of data for sentrifugo installed on a web server

**Comment by MiSAKACHi** [comment]
Apache supports the following modules:

 `mod_security`
- acts as a WAF that intercepts XSS, SQL Injection Attacks and more

`mod_evasive`
- protects your server from DoS Attacks

`SSL`
- Install SSL support on your server to prevent data sniffing by malicious users

Proper configuration of Apache is also vital to secure all web applications that are hosted on your server.
