### ISSUE TITLE
HTTP ERROR 500 when i visit http://192.xxx.xxx.my_ip_address/index.php/wizard/configuresite

### ISSUE THREAD

**Issue by Hamfri** [sapplica/sentrifugo#44]
Have installed Sentrifugo 2.1.1 Properly on ubuntu 16.04 using PHP version 7.0 but when i try to visit the link http://192.168.1.42/aimsoft_hr/index.php/wizard/configuresite i get a  **HTTP ERROR 500**. What could be the cause of this and yet all other links for configuration are working properly?
![can t](https://cloud.githubusercontent.com/assets/3530884/17933741/ec471ef2-6a1d-11e6-8bdf-02b5173750c3.png)

**Comment by Uris-Chan** [comment]
Hi,

I am encountering this same issue. My Sentrifugo 2.2.1 is running on;
- CentOS 7 (latest kernel)
- PHP 5.6
- MariaDB 5.5.50-1
- Apache 2.4.6-40

Selinux was set to enforced but I change it to permissive and the error still occurs

I tried turning on display_errors and display_startup_errors but I don't see anything in my /var/log/httpd/error_log either

If I skip site config, I can't add a Country to my Organisation config. The country is blank

![2016-09-02 19_09_06-sentrifugo - open source hrms](https://cloud.githubusercontent.com/assets/12781081/18202212/2f3a1352-7141-11e6-9584-c710c736d819.png)

**Comment by sapplica** [comment]
@Hamfri 
Hi,
The existing version of Sentrifugo does not support PHP version 7.0. The next version of Sentrifugo will be able to support PHP version 7.0. Thanks!

**Comment by sapplica** [comment]
@Uris-Chan 
Hi,
Sentrifugo does not support MariaDB.  Kindly switch to MySQL. Thanks!

**Comment by Uris-Chan** [comment]
Hi,

MariaDB is the community MySQL equivalent. MariaDB 5.5. is the equivalent of MySQL 5.5. In fact, CentOS/RHEL uses MariaDB from version 7 onwards.

My issue was fixed by downgrading from PHP 5.6 to PHP 5.4. Is there something incompatible with PHP 5.6?

**Comment by Hamfri** [comment]
@sapplica @Uris-Chan  Thank you all for your advice i will downgrade my PHP version to 5.4. @sapplica I was a little misguided by installation instructions where you said that one can use
![sentrifugo](https://cloud.githubusercontent.com/assets/3530884/18300598/1b1f9294-74d3-11e6-9c85-abf3a066cf0a.JPG)
 "PHP 5.3 or later"

**Comment by ghostfreeman** [comment]
Is there a timeframe for PHP 7 support?

**Comment by sapplica** [comment]
Hi,

@ghostfreeman PHP 7 support will be included in our next release. Our next release will be in this (November)  month. We will keep you posted!

**Comment by jarbro** [comment]
Still having this issue.  When will PHP7 support be coming?

**Comment by bensulli** [comment]
I'm hitting this too with both nginx and apache2 (tried both thinking nginx was the problem). Nothing is getting written to the error log either, but Chrome says it's a 500 error.

**Comment by abdul-khaliq** [comment]
@bensulli Same issue with my nginx. Vertual host config as below.

`server {

    listen 80;
    listen [::]:80;

    root /var/www/hrms/;
    index index.php index.html;
    access_log /var/log/nginx/sls.hrm/access.log;
	error_log /var/log/nginx/sls.hrm/error.log;

    server_name sls.hrm www.sls.hrm;

    location ~ \.php$ {
		include snippets/fastcgi-php.conf;
		fastcgi_pass unix:/run/php/php7.0-fpm.sock;
	}

	
	location ~ /\.ht {
		deny all;
	}

	location @rewrites {
	    if ($uri ~* ^/([a-z]+)$) {
	        set $page_to_view "/$1.php";
	        rewrite ^/([a-z]+)$ /$1.php last;
	    }
	}

	location / {
	    try_files $uri $uri/ /index.php?$args;
	}

}`

**Comment by ghost** [comment]
There is no problem with PHP version now, The actual problem is php-xml, Install, enable, and restart webserver.

sudo apt-get install php7.0-xml   ( or )    sudo apt-get install php5.6-xml
sudo service apache2 restart      ( or )    sudo service php-fpm restart && service nginx restart

**Comment by sbrijesh12** [comment]
Thank you much..now working after installed php5.6-xml package.

**Comment by Hamfri** [comment]
This issue was resolved and therefore i don't see a need to keep it open.
