### ISSUE TITLE
Installation Issue - Cannot get past Step 3

### ISSUE THREAD

**Issue by masterpiece91** [sapplica/sentrifugo#46]
No matter what I try, I get the following error: "Some error,please try again."

I have tried in several browsers; Chrome, firefox, safari.

How do I get passed this?

<img width="936" alt="2016-09-05_2355" src="https://cloud.githubusercontent.com/assets/3585303/18262392/c8bdd680-73c6-11e6-9f22-77e7e3070490.png">

**Comment by masterpiece91** [comment]
I did some further research to see if maybe my email was not meeting the regex criteria found in https://github.com/sapplica/sentrifugo/blob/4c5f09eb34e7df835d1eaa098b701b8d83adb6ae/install/step3.php but according to that regex, it is a valid email.

**Comment by masterpiece91** [comment]
I am looking at the code, and I don't quite understand how you can be trying to update a table that does not exist. That seems to be the problem. I cannot find a place in your repo where you are creating the database, which leads me to believe there is a db that I need to import. Is this correct, or am I missing something?

**Comment by masterpiece91** [comment]
Ok found the issue... it seems that the user that sql users has to have superadmin access such as the 'root' user... once i changed that... i was able to get this thing installed. Thanks!

I hope this helps someone else.

**Comment by skwdenyer** [comment]
I just ran into the same problem. Looking at the Step 3 code, it creates a simple query. Running that query manually in the mysql console resulted in:

ERROR 1436 (HY000): Thread stack overrun:  11200 bytes used of a 131072 byte stack, and 128000 bytes needed.  Use 'mysqld --thread_stack=#' to specify a bigger stack.

Hmm. So editing /etc/my.cnf to read:

thread_stack = 256K

and re-starting mysqld made this problem go away. YMMV, but this might help.
