### ISSUE TITLE
Manager not able to view employees expenses

### ISSUE THREAD

**Issue by GyanMatrixTech** [sapplica/sentrifugo#52]
And the Employee added the expense the reporting manager couldn't view the expense under the my employee expenses

**Comment by sapplica** [comment]
Hi,

The Reporting Manager will be able to able view the expense only after the employee submits the expense.

**Comment by GyanMatrixTech** [comment]
![image](https://cloud.githubusercontent.com/assets/23026471/19686542/318eeca0-9adf-11e6-89ad-8ad2697eb395.png)

Yes even after the employee submits the expense, the reporting manager couldn see it.

**Comment by GyanMatrixTech** [comment]
Found the solution, Submit button is in the View page!
