### ISSUE TITLE
Cronjob

### ISSUE THREAD

**Issue by jireh269** [sapplica/sentrifugo#61]
I've added employees in bulk using the import option, but when I try to send emails to employees for their login details, nothing happens. Browsers display a blank page (all white, no error code & messages).

I've tried:

1. Running 192.168.0.254/Sentrifugo/index.php/cronjob on a Chrome & Firefox browsers on Windows Server where the app resides.

2. Running localhost/Sentrifugo/index.php/cronjob on a Chrome & Firefox browsers on Windows Server where the app resides.

3. Running 192.168.0.254/Sentrifugo/index.php/cronjob on Chrome & Firefox browsers on my laptop.

Am I missing something? 
Please help me, thank you.

**Version: 3.0**

![cron](https://cloud.githubusercontent.com/assets/14177132/20584531/5af9ad12-b22e-11e6-8aaa-b9299f68386f.jpg)

**Comment by sapplica** [comment]
Hi,

Kindly check if the users are getting emails with the login credentials.

**Comment by jireh269** [comment]
Hi,

Users weren't able to receive emails.

What I've tried so far:

1. Disable Windows Firewall to all users and to the server.
2. Open all ports from the Firewall.

Please help, thank you.

**Comment by sapplica** [comment]
Hi,

@jireh269 Please update your mail settings through the Super Admin account. Go to: User menu on top right corner -> Mail Settings

**Comment by jireh269** [comment]
Hi Sapplica Team,

Ok, I tried changing the Super Admin email from Gmail to a YMail account, then changed the mail settings to match with Yahoo's SMTP settings.

Unfortunately, users still haven't receive emails from my app.

Please find attached screenshots for every steps I've made:

![error2](https://cloud.githubusercontent.com/assets/14177132/20779633/acb99bf8-b7b0-11e6-8dc5-5936b0f23ce0.jpg)
![error1](https://cloud.githubusercontent.com/assets/14177132/20779639/b68bed48-b7b0-11e6-95af-a1b17ce5433b.jpg)
![error3](https://cloud.githubusercontent.com/assets/14177132/20779649/bde532a2-b7b0-11e6-8702-887286db6d8b.jpg)

P.S. I'm from version 3.0 Beta to 3.0

**Comment by sapplica** [comment]
Hi,

Kindly try adding an employee and run the Cron job. Check if the employee receives an email with login credentials. Thank you!

**Comment by jireh269** [comment]
Hi Sapplica Team,

I. I've added an employee using One-at-a-Time (HR > Employees > Add), and the user received her username and password.

II. I've added an employee using Bulk (HR > Employees > Import), and it added successfully to the database. Now I logout, then run the cronjob (localhost/Sentrifugo/index.php/cronjob) on my Chrome browser, and nothing.... just a blank white page. No notifications whatsoever.
I tried to check if the users got emails, but they reported nothing.

It will be fine by me to add user one at a time, however I've already added 500+ users (using bulk method) and I can no longer remove them because of the standard (use Inactive).

Is there a way where I can see the log/error file from running a cronjob?

**Comment by jireh269** [comment]
UPDATE:

As I go through back to the Installation guide, I somehow missed the last instruction there (OpenSSL instruction). I don't know if failing to follow this instruction causes cronjob issues. But anyways, I tried to follow the link but it's not working anymore. I tried to go to the Official Site of OpenSSL, unfortunately they no longer distribute any code in binary form (https://www.openssl.org/community/binaries.html). So I tried to check their informal list of third-party products found on their wiki, and select the first link which is: OpenSSL for Windows (https://slproweb.com/products/Win32OpenSSL.html).
And from there I selected the first link which is: **Win32 OpenSSL v1.1.0c Light**
After that I installed OpenSSL on Windows directory.

Now my questions are:
1. How would I know if my OpenSSL is working good with my Sentrifugo application.
2. I tried running localhost/Sentrifugo/index.php/cronjob again after OpenSSL installation, but still no emails sent to employees that are added in bulk. Are there any other prerequisites that I might missed for cronjob to work?
3. I've been searching cronjob and it's all pointing to CronTab (CRON TAble) command-line program. But I'm pretty sure it's not compatible with my Windows Server 2008. Am I missing some software for cronjob to work?

Please help, thank you.

**Comment by jireh269** [comment]
Update:

**Case solved.**

I went to the database and delete all rows from _main_cronstatus_ table, and run cronjob again, and it works.
