### ISSUE TITLE
Query on Cron Jobs.

### ISSUE THREAD

**Issue by CarBee** [sapplica/sentrifugo#62]
Please let me know the URL used for running CRON jobs. Do we need to configure it in DB.

I can able to run the default CRON Job using the below URL which sents the Unsent emails.(indexAction)
localhost/sentrifugo/index.php/cronjob

**Want your help to configure CRON Jobs such as** 
_localhost/sentrifugo/index.php/cronjob/leaveapprove
localhost/sentrifugo/index.php/cronjob/requisition
localhost/sentrifugo/index.php/cronjob/inactiveusers
localhost/sentrifugo/index.php/cronjob/logcron
localhost/sentrifugo/index.php/cronjob/empexpiry
localhost/sentrifugo/index.php/cronjob/empdocsexpiry_

Also wanted to know how to configure **CRON jobs for Timemanagement.**

Thanks
Thangaraj N

**Comment by sapplica** [comment]
Hi,

@CarBee In Sentrifugo, below are the list of Cron jobs used:
Default Cron job: http://localhost/Sentrifugo/index.php/cronjob is sufficient to perform the email actions throughout the application.
Time Management Cron job: http://localhost/Sentrifugo/index.php/timemanagement/cronjob
Employee Documents Expiry Cron job: http://localhost/Sentrifugo/index.php/cronjob/empdocsexpiry
