### ISSUE TITLE
Providing Single Sign on.

### ISSUE THREAD

**Issue by CarBee** [sapplica/sentrifugo#71]
It would be great if you could provide enablement of Single sign on. At least if you could provide me a Skeleton of that it would great to write custom code and implement.

Thanks

**Comment by sapplica** [comment]
Hi,

@CarBee Thank you for showing interest in our product! This change will involve a lot of code level and database changes. We will be unable to explain it to you theoretically. If you would like to have any customization done, kindly contact our sales team at sales@sentrifugo.com. Thank you!

**Comment by CarBee** [comment]
Thanks for the Quick Feedback
