### ISSUE TITLE
Option to Apply leaves for Weekends. 

### ISSUE THREAD

**Issue by CarBee** [sapplica/sentrifugo#86]
In case of 24X7 support their work days will be based on their shift roaster.  So there will not be defined weekends for the department.  It would be great if there is an option provided while configuring the weekends for department. At least   provide a configuration which would have 7 days working day and people can apply leaves for any day of the week.

**Comment by sapplica** [comment]
Hi,

Currently, in Sentrifugo Leave management options are based on Department. Shift wise weekend settings are not available in Sentrifugo.

**Comment by CarBee** [comment]
Would be great if it included.
