### ISSUE TITLE
Cannot update email address after import employee

### ISSUE THREAD

**Issue by ch-gz** [sapplica/sentrifugo#98]
Hi,

I just encountered this issue. After I import some employees, I found one employee's email is wrong, so I cannot change it through web ui, then I update one row at table **main_employees_summary**(just change email address). After that I want to use that employee's email to reset password at login page, but the web said email does not exist. Can you help me with this issue? Thanks a lot!

**Comment by sapplica** [comment]
Hi,

Kindly update the same details in 'main_users' and 'main_employees' tables of the database. Do get back to us, if the issue still persists. Thank you!

**Comment by ch-gz** [comment]
Thank you, I found that two tables. One more question, how can I just change password through db? I found the password are all encrypted and stored in mysql.

**Comment by ch-gz** [comment]
@sapplica Thank you , I found that two tables. One more question, how can I just change password for specific user? I found the password are all encrypted and stored in mysql.

**Comment by sapplica** [comment]
Hi,

Kindly run the below query in your database to change the password of a specific user.

Query: update main_users set emppassword=md5('example') where id=1;

NOTE: 1. You can provide any password instead of the word example.
           2. Provide the ID of the user in the place of 'id' in the above query.

**Comment by ch-gz** [comment]
@sapplica Thank you so much! It works like a charm!
